server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: informes-service
  datasource:
    url: jdbc:mysql://localhost:3310/clinica_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      citasService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      citasService:
        maxAttempts: 3  # Nombre correcto de propiedad
        waitDuration: 1000  # Duraci칩n en milisegundos
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
feign:
  client:
    config:
      pacientes-service:
        url: "http://localhost:8083"  # La URL de tu servicio citas-service, donde est치 corriendo en el puerto 8082
      cita-service:
        url: "http://localhost:8082"  # La URL de tu servicio citas-service, donde est치 corriendo en el puerto 8082
      personal-service:
        url: "http://localhost:8084"  # La URL de tu servicio citas-service, donde est치 corriendo en el puerto 8082
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
