server:
  port: 8087
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/clinica-realm
          jwk-set-uri: http://localhost:8080/realms/clinica-realm/protocol/openid-connect/certs
  quartz:
      job-store-type: jdbc
      jdbc:
        initialize-schema: always
      properties:
        org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        org.quartz.jobStore.useProperties: true
  datasource:
    url: jdbc:mysql://mysqldb:3306/clinica_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true





resilience4j:
  circuitbreaker:
    instances:
      stripeService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        wait-duration-in-open-state: 10s
      paypalService:
        failure-rate-threshold: 40
        minimum-number-of-calls: 5
        sliding-window-type: COUNT_BASED
        sliding-window-size: 15
        wait-duration-in-open-state: 15s
  retry:
    instances:
      stripeService:
        max-attempts: 3
        wait-duration: 1s
      paypalService:
        max-attempts: 2
        wait-duration: 2s

feign:
  client:
    config:
      citas-service:
        url: http://citas-service:8082
      pacientes-service:
        url: http://pacientes-service:8083

