spring:
  application:
    name: usuarios-service
  ddatasource:
    url: jdbc:mysql://mysqldb:3306/clinica_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/clinica-realm
          jwk-set-uri: http://localhost:8080/realms/clinica-realm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080
  realm: ecommerce
  resource: backend-client
  credentials:
    secret: yo4FUA11RWp45kwBMjAeAipaZXKLmRxs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8093
